name: Build Python
on:
  workflow_call:
    inputs:
      matrix:
        required: true
        type: string
      python-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      matrix:
        required: true
        type: string
        default: '[{"tag": "vsview", "package": "vsview", "path": ".", "build_args": "--sdist --wheel"}]'
        description: |
          JSON output from resolve_package.py

          Examples:
  
          - [{"tag": "vsview", "package": "vsview", "path": ".", "build_args": "--sdist --wheel"}]
          - [{"tag": "comp", "package": "vsview-comp", "path": "src/plugins/comp", "build_args": "--wheel"}]
      python-version:
        required: false
        type: string
        default: "3.14"

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(inputs.matrix) }}
    uses: ./.github/workflows/ci-lint.yml
    with:
      package: ${{ matrix.package }}
    secrets: inherit

  build:
    name: Build ${{ matrix.package }}
    needs: [lint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(inputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ inputs.python-version }}
          enable-cache: true

      - name: Generate SBOM
        run: uv export --package "${{ matrix.package }}" --no-dev --format cyclonedx1.5 -o "${{ matrix.path }}/sboms.json"

      - name: Build
        run: uv build --package "${{ matrix.package }}" ${{ matrix.build_args }} --out-dir dist --clear

      - name: Check the output
        run: uvx twine check --strict dist/*

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: dist-${{ matrix.package }}
          path: dist/
