name: Publish Native Package
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      python-version:
        required: true
        type: string

jobs:
  publish:
    name: Publish ${{ inputs.package-name }} to PyPI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    environment:
      name: pypi-${{ inputs.package-name }}
      url: https://pypi.org/p/${{ inputs.package-name }}

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: dist
          merge-multiple: true

      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ inputs.python-version }}
          enable-cache: false

      - name: Check the output
        run: uvx twine check --strict dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1

      - name: Post webhook for failure
        if: failure()
        uses: Jaded-Encoding-Thaumaturgy/discord-failure-notifier@fb70088dc5982abfac889fdded8603be4f5823b6 # v1
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
